### ISSUE TITLE
Support for Axon.ivy Engine 6.3

### ISSUE THREAD

**Issue by vnnvanhuong** [saigonwithlove/ivy-intellij#34]
Hi @cavoirom 

I have tried to set up this plugin using Axon.ivy Engineer 6.3 with my IntelliJ IDEA 2022.2.1 (Community Edition) on macOS 12.4. The Ivy plugin was activated successfully but I got the following error in the log:

```bash
2022-08-22 09:43:28,190 [  46979] SEVERE - #s.i.i.s.InitializationActivity - Could not create Ivy Engine.
java.util.NoSuchElementException: Could not create Engine with version: 6.3.0-server
	at saigonwithlove.ivy.intellij.engine.IvyEngineFactory.newEngine(IvyEngineFactory.java:51)
	at saigonwithlove.ivy.intellij.settings.InitializationActivity.lambda$createIvyEngineUpdater$11(InitializationActivity.java:134)
	at saigonwithlove.ivy.intellij.settings.CacheObserver.lambda$onNext$0(CacheObserver.java:38)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

It seemed like the plugin does not support this engine. Thank you for your checking in advance.

**Comment by cavoirom** [comment]
Hi @vnnvanhuong, I created [feature/ivy6](/saigonwithlove/ivy-intellij/tree/feature/ivy6) to implement Ivy 6.3.0 supporting. You can download the latest build from Github Action: <https://github.com/saigonwithlove/ivy-intellij/actions?query=branch%3Afeature%2Fivy6++>. I currently can provide the library, so that you can code in Intellij, run the project on Axon.ivy Engine is still not possible.

You need to do tho following steps to see the effect:

- Install Ivy Plugin.
- Set the Ivy Engine directory in settings.
- Restart Intellij.
- Setup the workspace for you Axon.ivy project.
- Open the workspace, if you see Ivy plugin window icon in the bottom area, it is activated.
- Restart IntelliJ to re-index the libraries from Ivy.

**Comment by cavoirom** [comment]
I landed the code to `master` branch. We can code and check compile error on IntelliJ, but could not run the Ivy Engine and deploy for now. It will address the deployment soon.
